### ISSUE TITLE
bindings: python: migrate metadata out of setup.py to pyproject.toml

### ISSUE THREAD

**Issue by vfazio** [brgl/libgpiod#107]
PyPA recommends migrating to pyproject.toml where possible: https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

We have one, but it's sparse. We do not explicitly specify the build-backend:

```toml
[build-system]
requires = ["setuptools>=59.0.0", "packaging"] # we need 59.0.0 for https://github.com/pypa/setuptools/commit/974dbb03769a500c5077d37291817f30359a0d7b
build-backend = "setuptools.build_meta"
```

I don't think we need "wheel" as a dependency to generate wheels (testing shows we don't at least).

As part of the migration, we can specify proper Trove classifiers. Newer versions of setuptools support dynamic fields in the toml file.

More configuration will slowly start landing in the toml file as a result of #97, so we may as well make it comprehensive.
